name: echo
on: push

jobs:
  echo_task:
    name: Install Python 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
      - name: run python file
          run: python what_is_your_name.py


